# -*- coding: utf-8 -*-
"""DataLoad.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PF7ZBCOkHhiL8RK7o-YX9uIRs0LjHOuM
"""

import argparse
import pandas as pd
import os
import glob

def dataload(dir):
  directory = dir
  data_list = glob.glob(os.path.join(directory, '*.dat'))

  allData = []
  for file in data_list:
    df = pd.read_csv(file, sep="	", encoding="utf-16", header=None)
    allData.append(df)
  F1 = pd.concat(allData, axis=0, ignore_index=True)
  return F1