# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199ELcGztEBNdXOWtwvEm4eTJVJn-vCJz
"""

import argparse
import pandas as pd
import os
import glob

from seperate import *
from dataload import *
from wr import *
from field import *

if __name__ == "__main__":
  parser = argparse.ArgumentParser(description="Field Spectra to Excel")
  parser.add_argument("--data_dir", default="/content/drive/MyDrive", type=str, help="Directory where the data is located")
  parser.add_argument("--num_shots", default=4, type=int, help="Number of shots per Depth")
  parser.add_argument("--save_dir", default="/content/drive/MyDrive", type=str, help="Directory where the data is saved")
  parser.add_argument("--save_name", default="New_Result", type=str, help="Name of field data what you save")
  parser.add_argument("--save_name_wr", default="New_Result_WR", type=str, help="Name of WR data what you save")
  args = parser.parse_args()

  DATA_DIR = args.data_dir
  NUM_SHOTS = args.num_shots
  SAVE_DIR = args.save_dir
  SAVE_NAME = args.save_name
  SAVE_NAME_WR = args.save_name_wr


  F1 = dataload(DATA_DIR)

  F1, F_WR = seperate(F1)


  field(F1, NUM_SHOTS, SAVE_DIR, SAVE_NAME)
  reference(F_WR, SAVE_DIR, SAVE_NAME_WR)