# -*- coding: utf-8 -*-
"""Seperate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19A2jPoSUMvE3De82rSYL66pC656Y056m
"""

import argparse
import pandas as pd
import os
import glob

def seperate(F1):
  F_WR = F1[F1[0].str.contains('white', case=False) | F1[0].str.contains('wr', case=False) | F1[0].str.contains('w', case=False) ]
  F_WR = F_WR.reset_index()
  F_WR = F_WR.drop(columns='index')

  F1 =  F1[~F1[0].str.contains('white', case=False) & ~F1[0].str.contains('wr', case=False) & ~F1[0].str.contains('w', case=False) ]
  F1 = F1.reset_index()
  F1 = F1.drop(columns='index')
  return F1, F_WR