# -*- coding: utf-8 -*-
"""WR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qSSNypNw6GTxy3Y5ERAFwRKWFr81fhaE
"""

import argparse
import pandas as pd
import os
import glob

def reference(F, save_dir, save_name_wr):
  F_WR = F
  # WR 데이터 뽑아내기
  # 데이터 필드포인트별로 각각 나눠주기
  n=0
  F_WR_list = []
  for i in range(0, F_WR.shape[0]//2151):
    A=2151*(i+1)
    globals()['F_WR_{0}'.format(i)] = F_WR.loc[n:A-1]
    F_WR_list.append('F_WR_{0}'.format(i))
    n = A



  # 전치행렬로 변환
  for i in range(0, F_WR.shape[0]//2151):
    globals()['F_WR_{0}'.format(i)] = globals()['F_WR_{0}'.format(i)].T



  # 데이터별 컬럼명 350~2500로 바꿔주기
  for i in range(0, F_WR.shape[0]//2151):
    globals()['F_WR_{0}'.format(i)].columns = list(range (350, 2501))



  # 필드 정보를 column 데이터로 만든 뒤 인덱스로 변환
  for i in range(0, F_WR.shape[0]//2151):
    Inform =  globals()['F_WR_{0}'.format(i)].iloc[0,0]
    Inform = Inform[11:-4]
    globals()['F_WR_{0}'.format(i)]["inform"] = Inform
    globals()['F_WR_{0}'.format(i)] = globals()['F_WR_{0}'.format(i)].drop(index=[0, 1, 2])
    col1 = globals()['F_WR_{0}'.format(i)].columns[-1:].to_list()
    col2 = globals()['F_WR_{0}'.format(i)].columns[:-1].to_list()
    new_col = col1 + col2
    globals()['F_WR_{0}'.format(i)] = globals()['F_WR_{0}'.format(i)][new_col]
    globals()['F_WR_{0}'.format(i)].set_index("inform", inplace=True)



  # 데이터들 하나로 병합
  if len(F_WR_list) > 2 :
    Result = pd.concat([F_WR_0, F_WR_1])
    for i in range(1,(F_WR.shape[0]//2151)-1):
      Result = pd.concat([Result, globals()['F_WR_{0}'.format(i+1)]])
  elif len(F_WR_list) == 2:
    Result = pd.concat([F_WR_0, F_WR_1])
  elif len(F_WR_list) == 1:
    Result = F_WR_0



  # 저장
  # 파일명 설정
  new_dr = save_dir
  file_name = save_name_wr
  new_name = new_dr + "/" + file_name + ".xlsx"
  if not os.path.exists(new_dr):
    os.mkdir(new_dr)
  Result.to_excel(new_name)